name: Flujo vacío de prueba final

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  nada:
    runs-on: ubuntu-latest
    name: Trabajo de prueba vacío
    steps:
      - name: Imprimir un saludo
        run: echo "Se ha detectado la Pull Request hacia main, pero no ejecuto nada más."
